// CONTAINER2/REUSABLE_WEB_COMPONENTS/VueDefault/frontend/src/components/NavBar.vue
﻿//TODO Web Template Studio: Add a new link in the NavBar for your page here. //
A skip link is included as an accesibility best practice. For more information
visit https://www.w3.org/WAI/WCAG21/Techniques/general/G1.
<template>
  <div>
    <div class="skipLink">
      <a href="#mainContent">Skip to Main Content</a>
    </div>
    <div
      class="
        navbar navbar-expand-sm navbar-light
        border-bottom
        justify-content-between
      "
    >
      <a class="navbar-brand" href="/" role="heading" aria-level="1"
        >wts.VueDefault</a
      >
      <b-nav class="navbar-nav"> </b-nav>
    </div>
  </div>
</template>

<script>
export default {
  name: "NavBar",
};
</script>

<style scoped>
.skipLink a {
  position: absolute;
  left: -100px;
  top: -100px;
}

.skipLink a:focus {
  position: fixed;
  z-index: 1000;
  top: 0;
  left: 0;
  padding: 10px;
  color: #ffffff;
  background: #000000;
}
</style>

// CONTAINER2/REUSABLE_WEB_COMPONENTS/AngularDefault/frontend/src/app/app-shell/nav-bar/nav-bar.component.ts
﻿import { Component, OnInit } from "@angular/core";
import { Location } from "@angular/common";

@Component({
  selector: "app-nav-bar",
  templateUrl: "./nav-bar.component.html",
  styleUrls: ["./nav-bar.component.css"],
})
export class NavBarComponent implements OnInit {
  skipLinkPath: string;
  constructor(private location: Location) {}

  ngOnInit() {
    this.skipLinkPath = `${this.location.path()}#mainContent`;
  }
}

﻿<div class="skipLink">
  <a
    [href]="skipLinkPath"
    title="Skip to Main Content"
    aria-label="Skip to Main Content"
  >
    Skip to Main Content
  </a>
</div>
<nav
  class="
    navbar navbar-expand-sm navbar-light
    border-bottom
    justify-content-between
  "
>
  <a
    class="navbar-brand"
    routerLink="/"
    title="wts.AngularDefault"
    aria-label="wts.AngularDefault"
    role="heading"
    aria-level="1"
  >
    wts.AngularDefault
  </a>
  <div class="navbar-nav"></div>
</nav>
